name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Nix
      uses: cachix/install-nix-action@v20

    - name: Install Nix dependencies
      run: nix-env -f default.nix -iA cloudflare-pages-deploy

    - name: Deploy to Cloudflare Pages
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        cloudflared pages deploy . --project-name="laged.dev"
